name: &name delete

max_epoch: 400
batch_size: 16
batch_size_valid: 8
seed: 0
max_grad_norm: 5

keep_nbest_models: 10
best_model_criterion: [sisdr, max]
save_checkpoint_interval: 50

algo: selfremixing
algo_conf:
  selfremixing_loss_weight: 1.0
  remixit_loss_weight: 0.0
  nsrc_to_remix: 3
  constrained_batch_shuffle: true
  channel_shuffle: true
  solver_mixconsis: false
  shuffler_mixconsis: true
  normalize: false
teacher_update:
  update_timing: epoch
  weight: 0.8

loss: mrl1
loss_conf:
  stft_params:
    - n_fft: 512
      win_length: 400
      hop_length: 160
      window: hann
    - n_fft: 1024
      win_length: 800
      hop_length: 320
      window: hann
    - n_fft: 2048
      win_length: 1600
      hop_length: 640
      window: hann
  solve_perm: true
  snr_max: 30
  logarithm: false
  threshold_with: reference
  only_denominator: false

# dataset-related
dataset: wsjmix
dataset_conf:
  num_train_data: 5120
  num_valid_data: 256
  params:
    audio_len: 7
    ref_is_reverb: true
    return_noise: false
    allow_non_overlap: true
    sample_rate: 8000
    normalization: true
workers: 8

# now we only support stft
frontend: stft
frontend_conf:
  n_fft: &n_fft 512
  win_length: 400
  hop_length: 160
  window: hann

# separator conf
separator: ConformerSeparator
separator_conf:
  input_dim: 257
  num_spk: 2
  predict_noise: true # total 3 masks
  adim: 256
  aheads: 4
  layers: 16
  linear_units: 1024
  positionwise_layer_type: linear
  positionwise_conv_kernel_size: 1
  normalize_before: true
  dropout_rate: 0.0
  input_layer: linear
  positional_dropout_rate: 0.0
  attention_dropout_rate: 0.0
  nonlinear: sigmoid
  conformer_pos_enc_layer_type: rel_pos
  conformer_self_attn_layer_type: rel_selfattn
  conformer_activation_type: swish
  use_macaron_style_in_conformer: true
  use_cnn_in_conformer: true
  conformer_enc_kernel_size: 33
  n_groups: 8

# optimizer conf
optimizer: adamw
optimizer_conf:
  lr: &lr 2.0e-04
  weight_decay: 1.0e-02
  eps: 1.e-08

# scheduler conf
scheduler: warmup
scheduler_conf:
  mode: steplr
  lr: *lr
  patience: 2
  factor: 0.98
  warmup_steps: 5000
  min_lr: 2.0e-05
  decay_start_epoch: 100

# wandb conf
use_wandb: false
wandb:
  project: selfremixing2
  name: *name

# mixed precision
amp_params:
  enabled: false
  init_scale: 1280
